-- dml - LECTURE_REVIEW.sql
-- 작성자: 황윤재

select * from lecture_review;

-- 1~10: 아주 만족 (9.0 ~ 10.0)
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '선생님이 정말 친절하시고 강의 내용이 귀에 쏙쏙 들어옵니다!', 1);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '비전공자라 걱정했는데 기초부터 탄탄하게 잡아주셔서 좋았습니다.', 2);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '실무 꿀팁을 많이 알려주셔서 취업 준비에 큰 도움이 됐어요.', 3);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '커리큘럼이 체계적이고 예제 코드가 다양해서 이해하기 쉬워요.', 4);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '질문하면 답변도 빠르고 피드백이 아주 구체적입니다.', 5);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '인생 강의입니다. 자바가 이렇게 재밌는지 처음 알았어요.', 6);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.0, '수업 자료가 잘 정리되어 있어서 복습하기 편합니다.', 7);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '강사님 딕션이 좋아서 집중이 잘 됩니다. 강추!', 8);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '프로젝트 진행할 때 멘토링해주신 게 신의 한 수였습니다.', 9);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '시설도 쾌적하고 수업 분위기도 너무 좋아요.', 10);

-- 11~20: 만족 (8.0 ~ 8.5)
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '전반적으로 만족스럽지만 진도가 조금 빠른 편입니다.', 1);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.0, '내용은 알찬데 쉬는 시간이 좀 더 있었으면 좋겠어요.', 2);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '기초 지식이 없으면 처음에 조금 힘들 수 있습니다.', 3);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '과제가 좀 많긴 하지만 실력 향상에는 확실히 도움 됩니다.', 4);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.0, '강의실 에어컨이 너무 빵빵해서 추운 거 빼곤 다 좋아요.', 5);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '설명은 잘해주시는데 목소리가 조금 작으신 것 같아요.', 6);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.0, 'SQL 파트가 설명이 아주 명쾌했습니다.', 7);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '교재보다는 강사님 PPT 위주로 수업해서 필기가 중요해요.', 8);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '팀 프로젝트 할 때 갈등 관리도 도와주셔서 좋았습니다.', 9);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.0, '아침 수업이라 힘들지만 보람 찹니다.', 10);

-- 21~30: 보통 및 건의사항 (7.0 ~ 7.5)
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '진도 따라가기가 조금 벅차네요. 보충 수업이 있었으면 좋겠습니다.', 1);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.0, '실습 시간이 조금 더 늘어났으면 하는 바람입니다.', 2);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '이론 설명이 길어서 오후에는 조금 졸려요.', 3);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '컴퓨터 사양이 조금 더 좋았으면 좋겠습니다.', 4);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.0, '질문할 타이밍 잡기가 조금 어려워요.', 5);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '교재 오타가 몇 개 보여서 수정이 필요해 보입니다.', 6);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '후반부 갈수록 너무 어려워져서 멘붕 왔어요.', 7);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.0, '와이파이가 가끔 끊기는 것 같아요.', 8);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '자습 공간이 좀 더 넓었으면 좋겠습니다.', 9);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '취업 상담 횟수를 늘려주셨으면 합니다.', 10);

-- 31~40: 짧은 평가 (다양한 점수)
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '최고의 강의!', 1);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '강사님 사랑해요', 2);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 6.0, '그저 그렇습니다.', 3);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '돈이 아깝지 않은 수업', 4);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '무난합니다.', 5);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.0, '열정적인 강의 감사합니다.', 6);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 5.5, '저랑은 강의 스타일이 좀 안 맞네요.', 7);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '개발자가 되고 싶다면 꼭 들으세요.', 8);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '굿굿', 9);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.0, '나쁘지 않음', 10);

-- 41~50: 구체적인 피드백 및 0.5점 단위 테스트
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '스프링 부트 설명해주실 때 의존성 주입 개념 완벽하게 이해했습니다.', 1);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 4.5, '진도가 너무 빨라서 비전공자는 따라가기 힘들어요. 기초 반을 따로 개설해주세요.', 2);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 8.5, '리액트랑 연동하는 부분에서 에러가 많았는데 끝까지 봐주셔서 감사합니다.', 3);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '마지막 프로젝트 발표회 때 피드백 주신 내용이 면접에서 큰 도움이 됐습니다.', 4);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 6.5, '강의 내용은 좋은데 주변 소음 때문에 집중이 잘 안 됐어요.', 5);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '매일 나가는 과제가 힘들긴 했지만 덕분에 코딩 실력은 확실히 늘었습니다.', 6);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 7.5, '자바스크립트 비동기 처리 부분 설명이 조금 더 자세했으면 좋겠습니다.', 7);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 10, '학원 시설, 커리큘럼, 강사님 실력 모든 게 완벽했습니다.', 8);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 2.5, '개인 사정으로 중도 하차했지만... 솔직히 너무 어려웠어요.', 9);
INSERT INTO LECTURE_REVIEW VALUES (LECTURE_REVIEW_SEQ.NEXTVAL, 9.5, '6개월 동안 고생 많으셨습니다! 취업해서 찾아뵐게요.', 10);

-- [필수] 저장
COMMIT;