-- 커리큘럼 / curriculum

-- Java 기반 풀스택 개발자 양성 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 1, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 1, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 1, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 1, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 1, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 1, 8);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '14일', 1, 19);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 1, 26);

-- Spring Boot & React 실무 프로젝트 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 2, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 2, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 2, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 2, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 2, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '5일', 2, 9);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '4일', 2, 14);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 2, 19);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 2, 20);


-- 전자정부 프레임워크 기반 공공 SI 개발자 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 3, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 3, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 3, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 3, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 3, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 3, 17);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '14일', 3, 18);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '14일', 3, 21);


-- 클라우드(AWS) 기반 MSA 융합 개발자 양성
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 4, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 4, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 4, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 4, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 4, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 4, 14);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 4, 18);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 4, 19);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 4, 21);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 4, 26);

-- 차세대 보안 관제 및 정보보호 전문가 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 5, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 5, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 5, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 5, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 5, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '21일', 5, 27);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 5, 28);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 5, 29);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 5, 30);

-- Python 활용 빅데이터 분석 및 시각화 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 6, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 6, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 6, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 6, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 6, 5);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 6, 6);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 6, 7);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '10일', 6, 8);

-- AI 인공지능 서비스 기획 및 개발자 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 7, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 7, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 7, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 7, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 7, 5);

-- Node.js 백엔드 서버 개발자 실무 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 8, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 8, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 8, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 8, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 8, 5);

-- Vue.js 프론트엔드 전문 개발자 양성 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 9, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 9, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 9, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 9, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 9, 5);

-- 스마트 팩토리 SW 개발 전문가 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 10, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 10, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 10, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 10, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 10, 5);

-- IoT(사물인터넷) 융합 임베디드 SW 개발자 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 11, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 11, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 11, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 11, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 11, 5);

-- 금융 IT 핀테크 서비스 개발자 양성 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 12, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 12, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 12, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 12, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 12, 5);

-- 블록체인 기반 응용 소프트웨어 개발자 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 13, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 13, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 13, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 13, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 13, 5);

-- 자율주행 데이터 처리 및 AI 모델링 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 14, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 14, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 14, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 14, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 14, 5);

-- 메타버스 및 XR 실감형 콘텐츠 제작 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 15, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 15, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 15, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 15, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 15, 5);

-- C# .NET 스마트 윈도우 프로그래밍 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 16, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 16, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 16, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 16, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 16, 5);

-- 코틀린(Kotlin) 기반 안드로이드 앱 개발 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 17, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 17, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 17, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 17, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 17, 5);

-- 유니티(Unity) 게임 클라이언트 개발자 양성
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 18, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 18, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 18, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 18, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 18, 5);

-- 데브옵스(DevOps) 및 CI/CD 인프라 구축 전문가

insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 19, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 19, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 19, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 19, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 19, 5);

-- SAP ABAP 엔터프라이즈 솔루션 개발 과정
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '30일', 20, 1);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 20, 2);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '2일', 20, 3);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '50일', 20, 4);
insert into CURRICULUM VALUES (CURRICULUM_SEQ.nextval, '7일', 20, 5);

commit;



-- 등록교사 / COURSE_INSTRUCTOR
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2024-01-02', '2024-06-30', 1,1);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2024-03-04', '2024-08-16', 2,2);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2024-05-01', '2024-11-27', 3,3);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2025-09-01', '2026-02-28', 1, 1);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2025-10-20', '2026-04-18', 3, 2);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2025-08-04', '2026-03-02', 4, 4);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2025-12-29', '2026-06-27', 6, 3);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2026-01-05', '2026-08-03', 8, 5);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2026-01-26', '2026-03-25', 10, 6);
INSERT INTO COURSE_INSTRUCTOR VALUES (COURSE_INSTRUCTOR_SEQ.nextval, '2026-03-26', '2026-07-25', 9, 6);

commit;





-- 사물함 개인 배정 /
select * from locker;
select * from student;
select * from REGISTERED_COURSE;
select * from PERSONAL_LOCKER;
-- 진행중인 과정의 4를 듣는 학생들의 개인사물함
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 91, 1);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 92, 2);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 93, 3);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 94, 4);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 95, 5);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 96, 6);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 97, 7);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 98, 8);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 99, 9);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 100, 10);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 101, 11);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 102, 12);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 103, 13);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 104, 14);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 105, 15);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 106, 16);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 107, 17);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 108, 18);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 109, 19);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-09-01', null, 110, 20);


-- 진행중인 과정의 5를 듣는 학생들의 개인사물함 강의실 2
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 111, 31);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 112, 32);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 113, 33);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 114, 34);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 115, 35);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 116, 36);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 117, 37);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 118, 38);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 119, 39);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 120, 40);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 121, 41);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 122, 42);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 123, 43);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 124, 44);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 125, 45);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 126, 46);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 127, 47);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 128, 48);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 129, 49);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-10-20', null, 130, 50);


-- 진행중인 과정의 6을 듣는 학생들의 개인사물함 강의실 4
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 131, 91);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 132, 92);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 133, 93);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 134, 94);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 135, 95);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 136, 96);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 137, 97);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 138, 98);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 139, 99);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 140, 100);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 141, 101);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 142, 102);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 143, 103);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 144, 104);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 145, 105);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 146, 106);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 147, 107);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 148, 108);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 149, 109);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 150, 110);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 151, 111);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 152, 112);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 153, 113);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 154, 114);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-08-04', null, 155, 115);


-- 진행중인 과정의 7을 듣는 학생들의 개인사물함 강의실 3
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 156, 61);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 157, 62);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 158, 63);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 159, 64);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 160, 65);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 161, 66);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 162, 67);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 163, 68);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 164, 69);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 165, 70);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 166, 71);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 167, 72);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 168, 73);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 169, 74);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 170, 75);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 171, 76);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 172, 77);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 173, 78);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 174, 79);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 175, 80);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 176, 81);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 177, 82);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 178, 83);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 179, 84);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 180, 85);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 181, 86);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 182, 87);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2025-12-29', null, 183, 88);


-- 진행중인 과정의 8을 듣는 학생들의 개인사물함 강의실 5
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 184, 117);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 185, 118);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 186, 119);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 187, 120);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 188, 121);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 189, 122);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 190, 123);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 191, 124);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 192, 125);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 193, 126);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 194, 127);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 195, 128);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 196, 129);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 197, 130);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 198, 131);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 199, 132);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 200, 133);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 201, 134);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 202, 135);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 203, 136);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 204, 137);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 205, 138);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 206, 139);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-05', null, 207, 140);

-- 진행중인 과정의 9를 듣는 학생들의 개인사물함 강의실 6
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 208, 143);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 209, 144);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 210, 145);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 211, 146);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 212, 147);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 213, 148);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 214, 149);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 215, 150);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 216, 151);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 217, 152);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 218, 153);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 219, 154);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 220, 155);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 221, 156);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 222, 157);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 223, 158);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 224, 159);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 225, 160);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 226, 161);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 227, 162);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 228, 163);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 229, 164);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 230, 165);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 231, 166);
insert into PERSONAL_LOCKER (PERSONALLOCKERSEQ, PERSONALLOCKERALLOCATIONDATE, PERSONALLOCKERENDDATE, STUDENTSEQ, LOCKERSEQ) VALUES (PERSONAL_LOCKER_SEQ.nextval, '2026-01-26', null, 232, 167);




-- 컴퓨터 배인 배정
--
-- 진행중인 과정의 4를 듣는 학생들의 개인컴퓨터
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 91, 1);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 92, 2);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 93, 3);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 94, 4);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 95, 5);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 96, 6);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 97, 7);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 98, 8);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 99, 9);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 100, 10);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 101, 11);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 102, 12);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 103, 13);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 104, 14);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 105, 15);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 106, 16);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 107, 17);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 108, 18);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 109, 19);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-09-01', null, 110, 20);


-- 진행중인 과정의 5를 듣는 학생들의 개인컴퓨터 강의실 2
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 111, 31);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 112, 32);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 113, 33);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 114, 34);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 115, 35);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 116, 36);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 117, 37);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 118, 38);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 119, 39);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 120, 40);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 121, 41);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 122, 42);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 123, 43);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 124, 44);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 125, 45);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 126, 46);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 127, 47);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 128, 48);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 129, 49);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-10-20', null, 130, 50);


-- 진행중인 과정의 6을 듣는 학생들의 개인컴퓨터 강의실 4
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 131, 91);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 132, 92);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 133, 93);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 134, 94);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 135, 95);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 136, 96);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 137, 97);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 138, 98);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 139, 99);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 140, 100);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 141, 101);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 142, 102);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 143, 103);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 144, 104);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 145, 105);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 146, 106);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 147, 107);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 148, 108);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 149, 109);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 150, 110);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 151, 111);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 152, 112);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 153, 113);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 154, 114);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-08-04', null, 155, 115);


-- 진행중인 과정의 7을 듣는 학생들의 개인컴퓨터 강의실 3
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 156, 61);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 157, 62);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 158, 63);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 159, 64);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 160, 65);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 161, 66);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 162, 67);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 163, 68);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 164, 69);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 165, 70);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 166, 71);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 167, 72);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 168, 73);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 169, 74);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 170, 75);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 171, 76);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 172, 77);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 173, 78);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 174, 79);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 175, 80);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 176, 81);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 177, 82);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 178, 83);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 179, 84);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 180, 85);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 181, 86);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 182, 87);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2025-12-29', null, 183, 88);


-- 진행중인 과정의 8을 듣는 학생들의 개인컴퓨터 강의실 5
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 184, 117);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 185, 118);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 186, 119);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 187, 120);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 188, 121);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 189, 122);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 190, 123);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 191, 124);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 192, 125);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 193, 126);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 194, 127);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 195, 128);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 196, 129);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 197, 130);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 198, 131);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 199, 132);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 200, 133);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 201, 134);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 202, 135);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 203, 136);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 204, 137);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 205, 138);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 206, 139);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-05', null, 207, 140);

-- 진행중인 과정의 9를 듣는 학생들의 개인컴퓨터 강의실 6
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 208, 143);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 209, 144);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 210, 145);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 211, 146);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 212, 147);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 213, 148);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 214, 149);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 215, 150);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 216, 151);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 217, 152);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 218, 153);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 219, 154);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 220, 155);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 221, 156);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 222, 157);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 223, 158);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 224, 159);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 225, 160);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 226, 161);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 227, 162);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 228, 163);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 229, 164);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 230, 165);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 231, 166);
insert into PERSONAL_COMPUTER (personalcomputerseq, personalcomputerallocationdate, personalcomputerenddate, studentseq, computerseq) values (PERSONAL_COMPUTER_SEQ.nextval, '2026-01-26', null, 232, 167);

commit;