-- 컴퓨터 DML 창고에 있는 null값은 다시 넣어야함

select * from COMPUTER;

delete COMPUTER;

CREATE SEQUENCE computer_Seq;
DROP SEQUENCE computer_Seq;

-----------------------------------------------------------------------------------------1강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 1); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 1); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 1); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 1);


-----------------------------------------------------------------------------------------2강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 2); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 2); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 2); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 2); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 2); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 2);

-----------------------------------------------------------------------------------------3강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 3); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 3); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 3); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 3); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 3);

-----------------------------------------------------------------------------------------4강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 4); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 4); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 4); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 4); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 4);

-----------------------------------------------------------------------------------------5강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 5); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 5); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 5); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 5); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 5);


-----------------------------------------------------------------------------------------6강의실 컴퓨터
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 6); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 6); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 6); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, 6); -- 고장
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, 6);










-----------------------------------------------------------------------------------------창고 컴퓨터 ----- 추후 추가
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 3, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 4, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 4, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 3, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 3, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 4, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 4, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 1, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 3, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 2, NULL);
INSERT INTO COMPUTER VALUES (computer_Seq.NEXTVAL, 3, NULL);

commit ;

select count(*)
from COMPUTER where LECTURESEQ = 6;
