-- 교재 dml


INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 객체지향 설계 프로그래밍', '강오면', 1);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 리눅스 시스템 프로그래밍', '백철노', 2);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 네트워크 기초 최적화', '노지덕', 3);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 머신러닝 기초 입문', '안창바', 4);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 빅데이터 분석 이론', '윤윤도', 5);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 HTML5/CSS3 마스터', '조성바', 6);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 AWS 클라우드 인프라 입문', '안윤박', 7);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 Swift iOS 개발 최적화', '최철규', 8);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 직업 윤리 프로그래밍', '이서박', 9);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 AWS 클라우드 인프라 최적화', '남성문', 10);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 자료구조 최적화', '전주린', 11);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 소프트웨어 공학 최적화', '손서백', 12);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 컴퓨터 구조 최적화', '성가면', 13);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 AWS 클라우드 인프라 입문', '장범복', 14);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 소프트웨어 공학 마스터', '양찬섭', 15);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 정보보안 실무 입문', '임지도', 16);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 정보보안 실무 실무', '유동근', 17);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 리눅스 시스템 정석', '황시규', 18);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 데이터베이스 개론 마스터', '신우린', 19);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 JPA 데이터 매핑 실무', '유명룡', 20);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 머신러닝 기초 이론', '박석린', 21);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 JPA 데이터 매핑 최적화', '신아면', 22);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 직업 윤리 이론', '주성방', 23);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 리액트(React) 가이드', '신가면', 24);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 소프트웨어 공학 정석', '배명섭', 25);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 객체지향 설계 마스터', '최가봉', 26);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '핵심만 골라 배우는 Swift iOS 개발 프로그래밍', '문창문', 27);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 직업 윤리 정석', '노철나', 28);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 컴퓨터 구조 가이드', '문명림', 29);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '핵심만 골라 배우는 운영체제 입문', '오소미', 30);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 리액트(React) 프로그래밍', '노석방', 31);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 스프링 부트 마스터', '성무별', 32);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 안드로이드 앱 개발 실무', '박석근', 33);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 Node.js 서버 구축 실무', '구세기', 34);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 운영체제 최적화', '홍재권', 35);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 정보보안 실무 최적화', '백종국', 36);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 도커와 컨테이너 프로그래밍', '백서녀', 37);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '쉬운 SQL 활용 최적화', '심빈방', 38);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 Node.js 서버 구축 정석', '유유권', 39);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 객체지향 설계 정석', '박재선', 40);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 SQL 활용 프로그래밍', '엄예세', 41);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 Node.js 서버 구축 정석', '윤소문', 42);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 리액트(React) 마스터', '류이범', 43);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 자료구조 입문', '차중봉', 44);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 파이썬 입문 실무', '장종노', 45);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '핵심만 골라 배우는 빅데이터 분석 입문', '김우룡', 46);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 AWS 클라우드 인프라 정석', '차오남', 47);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 운영체제 마스터', '이가빈', 48);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 알고리즘 이론', '심지배', 49);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 리눅스 시스템 마스터', '차명구', 50);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 C언어 프로그래밍 프로그래밍', '권가산', 51);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 운영체제 프로그래밍', '서찬람', 52);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 리눅스 시스템 마스터', '지지민', 53);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '핵심만 골라 배우는 JavaScript 고급 최적화', '허종성', 54);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 자료구조 정석', '나안구', 55);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 운영체제 프로그래밍', '고준단', 56);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 소프트웨어 공학 이론', '신익세', 57);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 빅데이터 분석 실무', '임범복', 58);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 JPA 데이터 매핑 가이드', '임창바', 59);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 네트워크 기초 가이드', '고오묵', 60);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '핵심만 골라 배우는 유니티 게임 엔진 정석', '백가규', 61);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 정보보안 실무 가이드', '나다구', 62);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 자료구조 정석', '장영문', 63);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! 유니티 게임 엔진 이론', '문성민', 64);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 C언어 프로그래밍 입문', '신윤별', 65);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! C# 프로그래밍 입문', '강미남', 66);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 객체지향 설계 이론', '나찬나', 67);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 자료구조 가이드', '한복남', 68);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 자바 기초 입문', '전진사', 69);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '이것이 객체지향 설계 입문', '양명노', 70);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 리액트(React) 실무', '황오보', 71);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '혼자서도 잘하는 데이터베이스 개론 프로그래밍', '이창바', 72);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '실무에서 바로 쓰는 AWS 클라우드 인프라 정석', '나안람', 73);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '모던 데이터베이스 개론 최적화', '전아배', 74);
INSERT INTO Book VALUES (book_seq.NEXTVAL, '도전! SQL 활용 이론', '구복상', 75);
--INSERT INTO Book VALUES (book_seq.NEXTVAL, '열혈 파이썬 입문 마스터', '엄원단', 76);
commit;